#!/usr/bin/env bash
# EIF cold-start SFT wrapper — delegates to shared cold-start SFT.
#
# Maps EIF_* env vars to RL_PIPELINE_* and calls examples/shared/run_cold_start_sft.sh.

set -euo pipefail
set -x

# Map EIF_* -> RL_PIPELINE_*
export RL_PIPELINE_SFT_INPUT_PATH="${EIF_SFT_INPUT_PATH:-$HOME/data/hero_source/source_generated.parquet}"
export RL_PIPELINE_SFT_DATA_DIR="${EIF_SFT_DATA_DIR:-$HOME/data/openmathreasoning_hero_sft}"
export RL_PIPELINE_SFT_OUTPUT_DIR="${EIF_SFT_OUTPUT_DIR:-checkpoints/eif/eif_cold_start_sft}"
export RL_PIPELINE_MODEL_PATH="${EIF_MODEL_PATH:-Qwen/Qwen3-4B-Base}"
export RL_PIPELINE_TRUST_REMOTE_CODE="${EIF_TRUST_REMOTE_CODE:-True}"

export RL_PIPELINE_QUESTION_COL="${EIF_QUESTION_COL:-question}"
export RL_PIPELINE_ANSWER_COL="${EIF_ANSWER_COL:-answer}"
export RL_PIPELINE_PROMPT_COL="${EIF_PROMPT_COL:-prompt}"
export RL_PIPELINE_REWARD_MODEL_COL="${EIF_REWARD_MODEL_COL:-reward_model}"
export RL_PIPELINE_RESPONSE_COL="${EIF_RESPONSE_COL:-responses}"
export RL_PIPELINE_PRIMARY_RESPONSE_INDEX="${EIF_PRIMARY_RESPONSE_INDEX:-0}"
export RL_PIPELINE_SFT_NUM_SAMPLES="${EIF_SFT_NUM_SAMPLES:-2000}"
export RL_PIPELINE_SFT_VAL_SIZE="${EIF_SFT_VAL_SIZE:-0}"
export RL_PIPELINE_SEED="${EIF_SEED:-42}"
export RL_PIPELINE_SFT_MAX_RESPONSE_CHARS="${EIF_SFT_MAX_RESPONSE_CHARS:-12000}"
export RL_PIPELINE_FORCE_SFT_PREPROCESS="${EIF_FORCE_SFT_PREPROCESS:-0}"

export RL_PIPELINE_SFT_NNODES="${EIF_SFT_NNODES:-1}"
export RL_PIPELINE_SFT_GPUS_PER_NODE="${EIF_SFT_GPUS_PER_NODE:-8}"
export RL_PIPELINE_SFT_TRAIN_BATCH_SIZE="${EIF_SFT_TRAIN_BATCH_SIZE:-64}"
export RL_PIPELINE_SFT_MICRO_BATCH_SIZE_PER_GPU="${EIF_SFT_MICRO_BATCH_SIZE_PER_GPU:-1}"
export RL_PIPELINE_SFT_MAX_LENGTH="${EIF_SFT_MAX_LENGTH:-9216}"
export RL_PIPELINE_SFT_MAX_TOKEN_LEN_PER_GPU="${EIF_SFT_MAX_TOKEN_LEN_PER_GPU:-12288}"
export RL_PIPELINE_SFT_TRUNCATION="${EIF_SFT_TRUNCATION:-error}"
export RL_PIPELINE_SFT_LR="${EIF_SFT_LR:-1e-5}"
export RL_PIPELINE_SFT_LR_SCHEDULER="${EIF_SFT_LR_SCHEDULER:-cosine}"
export RL_PIPELINE_SFT_LR_WARMUP_RATIO="${EIF_SFT_LR_WARMUP_RATIO:-0.1}"
export RL_PIPELINE_SFT_MIN_LR_RATIO="${EIF_SFT_MIN_LR_RATIO:-0.0}"
export RL_PIPELINE_SFT_TOTAL_EPOCHS="${EIF_SFT_TOTAL_EPOCHS:-2}"
export RL_PIPELINE_SFT_SAVE_FREQ="${EIF_SFT_SAVE_FREQ:-after_each_epoch}"
export RL_PIPELINE_SFT_TEST_FREQ="${EIF_SFT_TEST_FREQ:--1}"
export RL_PIPELINE_SFT_LOGGERS="${EIF_SFT_LOGGERS:-'[\"console\"]'}"
export RL_PIPELINE_SFT_EXPERIMENT_NAME="${EIF_SFT_EXPERIMENT_NAME:-eif_cold_start_sft_$(date +%Y%m%d_%H%M%S)}"
export RL_PIPELINE_SFT_PROJECT_NAME="eif_cold_start"
export RL_PIPELINE_SFT_CHECKPOINT_SAVE_CONTENTS="${EIF_SFT_CHECKPOINT_SAVE_CONTENTS:-"['model','optimizer','extra','hf_model']"}"
export RL_PIPELINE_SFT_MAX_CKPT_TO_KEEP="${EIF_SFT_MAX_CKPT_TO_KEEP:-1}"
export RL_PIPELINE_SFT_RESUME_MODE="${EIF_SFT_RESUME_MODE:-disable}"
export RL_PIPELINE_SFT_ATTN_IMPLEMENTATION="${EIF_SFT_ATTN_IMPLEMENTATION:-flash_attention_2}"

# Multi-node vars
if [[ -n "${EIF_SFT_NODE_RANK:-}" ]]; then
    export RL_PIPELINE_SFT_NODE_RANK="$EIF_SFT_NODE_RANK"
fi
if [[ -n "${EIF_SFT_MASTER_ADDR:-}" ]]; then
    export RL_PIPELINE_SFT_MASTER_ADDR="$EIF_SFT_MASTER_ADDR"
fi
if [[ -n "${EIF_SFT_MASTER_PORT:-}" ]]; then
    export RL_PIPELINE_SFT_MASTER_PORT="$EIF_SFT_MASTER_PORT"
fi

bash examples/shared/run_cold_start_sft.sh "$@"
