#!/usr/bin/env bash
# HERO cold-start SFT wrapper — delegates to shared cold-start SFT.
#
# Maps HERO_* env vars to RL_PIPELINE_* and calls examples/shared/run_cold_start_sft.sh.

set -euo pipefail
set -x

# Map HERO_* -> RL_PIPELINE_*
export RL_PIPELINE_SFT_INPUT_PATH="${HERO_SFT_INPUT_PATH:-$HOME/data/hero_source/source_generated.parquet}"
export RL_PIPELINE_SFT_DATA_DIR="${HERO_SFT_DATA_DIR:-$HOME/data/openmathreasoning_hero_sft}"
export RL_PIPELINE_SFT_OUTPUT_DIR="${HERO_SFT_OUTPUT_DIR:-checkpoints/hero_paper_reproduction/hero_cold_start_sft}"
export RL_PIPELINE_MODEL_PATH="${HERO_MODEL_PATH:-Qwen/Qwen3-4B-Base}"
export RL_PIPELINE_TRUST_REMOTE_CODE="${HERO_TRUST_REMOTE_CODE:-True}"

export RL_PIPELINE_QUESTION_COL="${HERO_QUESTION_COL:-question}"
export RL_PIPELINE_ANSWER_COL="${HERO_ANSWER_COL:-answer}"
export RL_PIPELINE_PROMPT_COL="${HERO_PROMPT_COL:-prompt}"
export RL_PIPELINE_REWARD_MODEL_COL="${HERO_REWARD_MODEL_COL:-reward_model}"
export RL_PIPELINE_RESPONSE_COL="${HERO_RESPONSE_COL:-responses}"
export RL_PIPELINE_PRIMARY_RESPONSE_INDEX="${HERO_PRIMARY_RESPONSE_INDEX:-0}"
export RL_PIPELINE_SFT_NUM_SAMPLES="${HERO_SFT_NUM_SAMPLES:-2000}"
export RL_PIPELINE_SFT_VAL_SIZE="${HERO_SFT_VAL_SIZE:-0}"
export RL_PIPELINE_SEED="${HERO_SEED:-42}"
export RL_PIPELINE_SFT_MAX_RESPONSE_CHARS="${HERO_SFT_MAX_RESPONSE_CHARS:-12000}"
export RL_PIPELINE_FORCE_SFT_PREPROCESS="${HERO_FORCE_SFT_PREPROCESS:-0}"

export RL_PIPELINE_SFT_NNODES="${HERO_SFT_NNODES:-1}"
export RL_PIPELINE_SFT_GPUS_PER_NODE="${HERO_SFT_GPUS_PER_NODE:-8}"
export RL_PIPELINE_SFT_TRAIN_BATCH_SIZE="${HERO_SFT_TRAIN_BATCH_SIZE:-64}"
export RL_PIPELINE_SFT_MICRO_BATCH_SIZE_PER_GPU="${HERO_SFT_MICRO_BATCH_SIZE_PER_GPU:-1}"
export RL_PIPELINE_SFT_MAX_LENGTH="${HERO_SFT_MAX_LENGTH:-9216}"
export RL_PIPELINE_SFT_MAX_TOKEN_LEN_PER_GPU="${HERO_SFT_MAX_TOKEN_LEN_PER_GPU:-12288}"
export RL_PIPELINE_SFT_TRUNCATION="${HERO_SFT_TRUNCATION:-error}"
export RL_PIPELINE_SFT_LR="${HERO_SFT_LR:-1e-5}"
export RL_PIPELINE_SFT_LR_SCHEDULER="${HERO_SFT_LR_SCHEDULER:-cosine}"
export RL_PIPELINE_SFT_LR_WARMUP_RATIO="${HERO_SFT_LR_WARMUP_RATIO:-0.1}"
export RL_PIPELINE_SFT_MIN_LR_RATIO="${HERO_SFT_MIN_LR_RATIO:-0.0}"
export RL_PIPELINE_SFT_TOTAL_EPOCHS="${HERO_SFT_TOTAL_EPOCHS:-2}"
export RL_PIPELINE_SFT_SAVE_FREQ="${HERO_SFT_SAVE_FREQ:-after_each_epoch}"
export RL_PIPELINE_SFT_TEST_FREQ="${HERO_SFT_TEST_FREQ:--1}"
export RL_PIPELINE_SFT_LOGGERS="${HERO_SFT_LOGGERS:-'[\"console\"]'}"
export RL_PIPELINE_SFT_EXPERIMENT_NAME="${HERO_SFT_EXPERIMENT_NAME:-hero_cold_start_sft_$(date +%Y%m%d_%H%M%S)}"
export RL_PIPELINE_SFT_PROJECT_NAME="hero_paper_reproduction"
export RL_PIPELINE_SFT_CHECKPOINT_SAVE_CONTENTS="${HERO_SFT_CHECKPOINT_SAVE_CONTENTS:-"['model','optimizer','extra','hf_model']"}"
export RL_PIPELINE_SFT_MAX_CKPT_TO_KEEP="${HERO_SFT_MAX_CKPT_TO_KEEP:-1}"
export RL_PIPELINE_SFT_RESUME_MODE="${HERO_SFT_RESUME_MODE:-disable}"
export RL_PIPELINE_SFT_ATTN_IMPLEMENTATION="${HERO_SFT_ATTN_IMPLEMENTATION:-flash_attention_2}"

# Multi-node vars
if [[ -n "${HERO_SFT_NODE_RANK:-}" ]]; then
    export RL_PIPELINE_SFT_NODE_RANK="$HERO_SFT_NODE_RANK"
fi
if [[ -n "${HERO_SFT_MASTER_ADDR:-}" ]]; then
    export RL_PIPELINE_SFT_MASTER_ADDR="$HERO_SFT_MASTER_ADDR"
fi
if [[ -n "${HERO_SFT_MASTER_PORT:-}" ]]; then
    export RL_PIPELINE_SFT_MASTER_PORT="$HERO_SFT_MASTER_PORT"
fi

bash examples/shared/run_cold_start_sft.sh "$@"
